### ISSUE TITLE
Not compatible with Ember v3.8

### ISSUE THREAD

**Issue by josemarluedke** [Addepar/ember-table#659]
I have tried to use `ember-table@2.0.0-beta.7` with Ember v3.8 and it doesn't work. All the cell values return `undefined` values.

In the PR #658, tests are failing only in the release and beta channels, in which demonstrates that ember-table is broken with these Ember versions.

**Comment by tylerturdenpants** [comment]
Maybe we should work together on updating this addition .  I have a new branch that  nearly removes the use of the old version of the ‘argument’ decorator and most of the tests pass. If we could get @twokul onboard we may be able to push it over the finish line.

**Comment by cyk** [comment]
@tylerturdenpants That's great news! I'd be happy to help where I can, however, my bandwidth is a bit limited this week and then I'm offline the following.

**Comment by tylerturdenpants** [comment]
@cyk @josemarluedke PR #660 has about 2/3 of the tests passing.  I'm pretty certain we can drop the `@argument` decorator.  The key to the remainder of the failing tests may be to duplicating the functionality when `@argument` with `{ defaultIfUndefined: true }` is used

**Comment by shankarsridhar** [comment]
Hello :) 
Any idea when this will be closes ?

**Comment by tylerturdenpants** [comment]
So it looks like the add on is being refactored to use classic classes and removing the dependency on @ember-decorator/argument. When that’s done it should be good to go (as far as I know). You could try pointing your package.json to point to master?

**Comment by josemarluedke** [comment]
I can confirm that master works with Ember v3.9. This can be closed now.
