### ISSUE TITLE
not working in ember version 4.0 and above

### ISSUE THREAD

**Issue by TheLooseCannon** [Addepar/ember-table#926]
[#19704 [CLEANUP] Remove template-compiler.registerPlugin](https://github.com/emberjs/ember.js/blob/v4.1.0-beta.1/CHANGELOG.md#v400-november-15-2021)

`this.registerPlugin is not a function` error throwing. 

on digging...i think its due to the usage of ember-cli-htmlbars@3.x which is atleast 3 years old. 

is there any plan/issues for updating ember-cli-htmlbars?

**Comment by mixonic** [comment]
Please see https://github.com/Addepar/ember-table/pull/919 and the 4.0 beta releases.
